// import type { NextPage } from 'next'
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styled from "styled-components";
import styles from "../styles/Home.module.css";


export async function getStaticProps(context) {
  try {
    const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=898");
    // const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=898');
    const { results } = await res.json();
    const pokemon = results.map((pokeman, index) => {
      const dexNumber = ("00" + (index + 1)).slice(-3);
      const image = `https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${dexNumber}.png`;
      return {
        ...pokeman,
        image,
      };
    });
    return {
      props: { pokemon },
    };
  } catch (err) {
    console.error(err);
  }
}

// const Home: NextPage = () => {
const Home = ({ pokemon }) => {
  // console.log(pokemon);

  const DexEntry = pokemon.map((pokemon, index) => {
    const Name = pokemon.name[0].toUpperCase() + pokemon.name.substring(1);
    const dexNumber = ("00" + (index + 1)).slice(-3);

    return (
      <div key={index}>
        {dexNumber} {Name}
        {/* <Link href={`/pokemon/${index + 1}`}> */}
        <Link href={`/pokemon/${pokemon.name}`}>
          <a><Image src={pokemon.image} height="250px" width="250px" /></a>
        </Link>
      </div>
    );
  });

  return (
    <>
      <Head>
        <title>Typescript Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.dexLayout}>{DexEntry}</div>
    </>
  );
};

export default Home;
